name = "freeway"
main = "./dist/worker.mjs"
compatibility_date = "2022-10-03"
compatibility_flags = [
  "streams_enable_constructors"
]
r2_buckets = [
  { binding = "CARPARK", bucket_name = "carpark-dev-0" },
  { binding = "DUDEWHERE", bucket_name = "dudewhere-dev-0" }
]

[build]
command = "npm run build"

# PROD!
[env.production]
account_id = "fffa4b4363a7e5250af8357087263b3a"
route = { pattern = "https://freeway.dag.haus/*", zone_id = "f2f8a5b1c557202c6e3d0ce0e98e4c8e" }
r2_buckets = [
  { binding = "CARPARK", bucket_name = "carpark-prod-0" },
  { binding = "DUDEWHERE", bucket_name = "dudewhere-prod-0" }
]

# Staging!
[env.staging]
account_id = "fffa4b4363a7e5250af8357087263b3a"
route = { pattern = "https://freeway-staging.dag.haus/*", zone_id = "f2f8a5b1c557202c6e3d0ce0e98e4c8e" }
r2_buckets = [
  { binding = "CARPARK", bucket_name = "carpark-staging-0" },
  { binding = "DUDEWHERE", bucket_name = "dudewhere-staging-0" }
]

# Test!
[env.test]
workers_dev = true
r2_buckets = [
  { binding = "CARPARK", bucket_name = "carpark-test-0" },
  { binding = "DUDEWHERE", bucket_name = "dudewhere-test-0" }
]

[env.test.vars]
DEBUG = "true"

[env.alanshaw]
workers_dev = true
account_id = "4fe12d085474d33bdcfd8e9bed4d8f95"
r2_buckets = [
  { binding = "CARPARK", bucket_name = "carpark-alanshaw-0", preview_bucket_name = "carpark-alanshaw-preview-0" },
  { binding = "DUDEWHERE", bucket_name = "dudewhere-alanshaw-0", preview_bucket_name = "dudewhere-alanshaw-preview-0" }
]

[env.alanshaw.vars]
DEBUG = "true"
